services:
  postgres:
    image: postgres:15
    container_name: erp_postgres
    restart: always
    env_file:
      - ../.env.prod
    ports:
      - "127.0.0.1:5432:5432"   # 🔒 LOCAL ONLY
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../schema/Version_1/01_Finance:/docker-entrypoint-initdb.d
      - ../schema/Version_1/02_Staging:/docker-entrypoint-initdb.d
      - ../schema/Version_1/03_Audit:/docker-entrypoint-initdb.d
      - ../schema/Version_1/04_Complaince:/docker-entrypoint-initdb.d
      - ../schema/Version_1/05_Business_Logic:/docker-entrypoint-initdb.d
      - ../conf/postgres.conf.prod:/etc/postgresql/postgresql.conf
      - ../conf/pg_hba.conf.prod:/etc/postgresql/pg_hba.conf
    networks:
      - erp_network
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
      - "-c"
      - "hba_file=/etc/postgresql/pg_hba.conf"

volumes:
  pgdata:

networks:
  erp_network:
