services:
  postgres:
    image: postgres:15
    container_name: erp_postgres
    restart: always
    env_file:
      - ../.env.prod
    ports:
      - "127.0.0.1:5432:5432"   # 🔒 LOCAL ONLY
    volumes:
      - pgdata:/var/lib/postgresql/data
      - wal_archive:/var/lib/postgresql/wal_archive
      - ../../recovery/recovery.signal:/var/lib/postgresql/data/recovery.signal
      - ../schema/Version_1:/docker-entrypoint-initdb.d
      - ../conf/postgres.conf.prod:/etc/postgresql/postgresql.conf
      - ../conf/pg_hba.conf.prod:/etc/postgresql/pg_hba.conf
    networks:
      - erp_network
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
      - "-c"
      - "hba_file=/etc/postgresql/pg_hba.conf"

volumes:
  pgdata:
  wal_archive:
  
networks:
  erp_network:
